Settings.contact_email = 'contact@nameframe.com'
Settings.telephone_number = '(814)-337-2185'
Settings.telephone_free = '1-877-713-2336'
Settings.fax = '814-333-4236'
Settings.address = '19051 Park Avenue Plaza'
Settings.city = 'Meadville'
Settings.state = 'PA'
Settings.postal = '1633'
Settings.base_price_with_frame = 59.95
Settings.base_price_without_frame = 24.95
Settings.bottom_matt_price = 5
Settings.ornamet_price = 5
Settings.photos_price = 5
Settings.small_nameframe = '10 5/8" x 14 5/8"'
Settings.medium_nameframe = '10 5/8" x 20 5/8"'
Settings.large_nameframe = '10 5/8" x 26 5/8"'
Settings.small_frame_width = 12.000
Settings.medium_frame_width = 18.000
Settings.large_frame_width = 24.000
Settings.frame_heigth = 8.000
Settings.orders_email = "orders@nameframe.com"
Settings.developers_emails = ["daniel.gaytan@crowdint.com", "bernardo.galindo@crowdint.com", "emmanuel.delgado@crowdint.com"]
Settings.work_hours = "Hours Monday - Friday 9 AM to 6 PM EST  Saturday 9 AM to 4 PM EST"
Settings.authorize_net_login = "45qAh4aD9Rte"
Settings.authorize_net_password = "66zaYDxa82THz39e"
Settings.authorize_net_test = false
